#!/bin/sh
$docker_id=scoresim1

zip -r scoresim.zip elasticsearch/
docker cp scoresim.zip $docker_id:/
docker exec -it $docker_id "/home/elasticsearch/elasticsearch/installScoresim"
docker exec -it $docker_id "/home/elasticsearch/elasticsearch/bin/elasticsearch"

#/Volumes/Transcend/app/elasticsearch-6.2.2/bin/elasticsearch-plugin remove ScoreSim
#/Volumes/Transcend/app/elasticsearch-6.2.2/bin/elasticsearch-plugin install -v file:///Volumes/Transcend/eclipse/ScoreSim/elasticsearch.zip
