version: '3.6'
services:
  scoresim01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: scoresim1
    environment:
      - node.name=scoresim01
      - cluster.name=scoresim-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=scoresim01,scoresim02,scoresim03
      - discovery.seed_hosts=scoresim02,scoresim03
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    networks:
      - default
    ports:
      - "9200:9200"
      - "9300:9300"


  scoresim02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: scoresim2
    environment:
      - node.name=scoresim02
      - cluster.name=scoresim-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=scoresim01,scoresim02,scoresim03
      - discovery.seed_hosts=scoresim01,scoresim02
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
    cap_add:
      - ALL
    privileged: true

  scoresim03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: scoresim3
    environment:
      - node.name=scoresim03
      - cluster.name=scoresim-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=scoresim01,scoresim02,scoresim03
      - discovery.seed_hosts=scoresim01,scoresim02
    networks:
      - default
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    environment:
      SERVER_NAME: 127.0.0.1
      ELASTICSEARCH_HOSTS: http://scoresim01:9200
      # XPACK_GRAPH_ENABLED: false
      # XPACK_ML_ENABLED: false
      # XPACK_REPORTING_ENABLED: false
      # XPACK_SECURITY_ENABLED: false
      # XPACK_WATCHER_ENABLED: false
    ports:
      - "5601:5601"
    networks:
      - default
    depends_on:
      - scoresim01
    restart: "unless-stopped"
